# Generated by Django 4.2.11 on 2024-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0003_auto_20240322_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
