# Generated by Django 4.2.11 on 2024-04-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0004_downloadingmovie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownloadingMovie',
            new_name='Downloading_Movie',
        ),
    ]
