# Generated by Django 4.2.11 on 2024-04-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0005_rename_downloadingmovie_downloading_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloading_movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='downloading_movie',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='downloading_movie',
            name='title',
        ),
        migrations.AddField(
            model_name='downloading_movie',
            name='download_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='downloading_movie',
            name='download_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Downloading', 'Downloading'), ('Failed', 'Failed')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='downloading_movie',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloading_movie',
            name='downloaded_from',
            field=models.CharField(blank=True, choices=[('YTS', 'YTS')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='downloading_movie',
            name='movie',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='media_management.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
