# Generated by Django 4.2.11 on 2024-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0006_remove_downloading_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloading_movie',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
