# Generated by Django 4.2.11 on 2024-05-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0008_series_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='media_management.genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, to='media_management.genre'),
        ),
    ]
