# Generated by Django 4.2.11 on 2024-05-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0009_alter_movie_genres_alter_series_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='release_date',
            new_name='first_air_date',
        ),
    ]
