# Generated by Django 4.2.11 on 2024-05-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0010_rename_release_date_series_first_air_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
