# Generated by Django 4.2.11 on 2024-06-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0012_series_number_of_episodes_series_number_of_seasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
    ]
