# Generated by Django 4.2.11 on 2024-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0013_alter_series_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
