# Generated by Django 4.2.11 on 2024-08-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0015_seriesgenre_rename_genre_moviegenre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegenre',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='seriesgenre',
            name='tmdb_id',
        ),
    ]
