# Generated by Django 4.2.20 on 2025-07-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0016_remove_moviegenre_tmdb_id_remove_seriesgenre_tmdb_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Downloading_Movie',
        ),
    ]
