# Generated by Django 4.2.11 on 2024-07-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0013_alter_series_options'),
        ('profiles', '0004_profileseries_profilemovie_profileepisode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileepisode',
            name='watched_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemovie',
            name='liked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemovie',
            name='watched_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='profileseries',
            name='current_episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media_management.episode'),
        ),
        migrations.AlterField(
            model_name='profileseries',
            name='liked',
            field=models.BooleanField(null=True),
        ),
    ]
