# Generated by Django 4.2.11 on 2024-08-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0013_alter_series_options'),
        ('profiles', '0005_alter_profileepisode_watched_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemovie',
            name='watched_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='profileepisode',
            unique_together={('profile', 'episode')},
        ),
        migrations.AlterUniqueTogether(
            name='profilemovie',
            unique_together={('profile', 'movie')},
        ),
    ]
