# Generated by Django 4.2.11 on 2024-08-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_watchlaterlist_continuewatchinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileepisode',
            name='watched',
        ),
        migrations.RemoveField(
            model_name='profilemovie',
            name='watched',
        ),
        migrations.RemoveField(
            model_name='profileseries',
            name='current_episode',
        ),
        migrations.RemoveField(
            model_name='profileseries',
            name='watched',
        ),
    ]
