# Generated by Django 4.2.11 on 2024-08-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0016_remove_moviegenre_tmdb_id_remove_seriesgenre_tmdb_id'),
        ('profiles', '0009_remove_profileepisode_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuewatchinglist',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_management.series'),
        ),
        migrations.AlterField(
            model_name='continuewatchinglist',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_management.movie'),
        ),
    ]
