# Generated by Django 4.2.11 on 2024-08-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_continuewatchinglist_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuewatchinglist',
            name='continue_watching_movies',
        ),
        migrations.RemoveField(
            model_name='continuewatchinglist',
            name='continue_watching_series',
        ),
        migrations.DeleteModel(
            name='WatchLaterList',
        ),
    ]
